### ISSUE TITLE
RACK_ENV is not properly passed in start command

### ISSUE THREAD

**Issue by dsabeti** [paketo-buildpacks/rackup#355]
When trying to push [a Sinatra app](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop/assets/service_broker) that includes [specific configurations associated with the Rack environment](https://github.com/cloudfoundry/cf-acceptance-tests/blob/aaba78e8cfd7b5ff0ece25972a3fe31ed801232e/assets/service_broker/service_broker.rb#L138-L145), we noticed that the Sinatra configuration was being ignored. We believe we've tracked it down to [this line in the buildpack](https://github.com/paketo-buildpacks/rackup/blob/e2cb59b714a7975f22dfa9d26429271c7ae43266/build.go#L51):

```
bundle exec rackup --env RACK_ENV=production -p ...
```

When we removed  `RACK_ENV=` from the start command, the app was configured correctly with the production config:
```
bundle exec rackup --env production -p ...
``` 

We also got the app to configure correctly by changing the start command to use the `RACK_ENV` environment variable instead of the `--env` flag:

```
RACK_ENV=production bundle exec rackup -p ...
```

We also verified that, without any of the above changes, the `RACK_ENV` environment variable has the literal string value `"RACK_ENV=production"`, with the `RACK_ENV=` prefix embedded in the value:
```
$ puts ENV['RACK_ENV']
RACK_ENV=production
```

## Expected Behavior
`RACK_ENV` should be set to a valid value such as `production`

## Current Behavior
`RACK_ENV` is currently being set incorrectly with a prefix of `RACK_ENV=`.

## Possible Solution
The buildpack can be updated to use either the flag or the environment variable as described above.

## Steps to Reproduce

1. Build [this app](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop/assets/service_broker) with the full Ruby CNB
2. Run the app
3. Curl `<app-address>:<app-port>/v2/catalog`
4. Observe the app returning a 500 Internal Server Error

**Comment by robdimsdale** [comment]
Fixed with #356 - closing.
